# This file was generated by GoReleaser. DO NOT EDIT.
cask "qurl" do
  version "2.4.0"

  on_macos do
    on_arm do
      sha256 "3c4209e6723ae083daae01ed9460d560be9ef232fb6767f7057064a2242810bc"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0ed05c0e71a8e737fe0992dae55a7d4e942d16722225794bc60a78d9427c9e6"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "88a2efe42481357e4e4918f08408fdc837461ba36df9ce9a0794eea9620e4efd"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1a835f1ccedeb74b743edc78ec5dfeda67c32315a84a6d57d8d14cfead951097"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qurl"
  desc "Publish and access protected resources"
  homepage "https://layerv.ai/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qurl"
  manpage "manpages/qurl-completion.1"
  manpage "manpages/qurl-daemon-run.1"
  manpage "manpages/qurl-daemon.1"
  manpage "manpages/qurl-delete.1"
  manpage "manpages/qurl-get.1"
  manpage "manpages/qurl-inspect.1"
  manpage "manpages/qurl-list.1"
  manpage "manpages/qurl-login.1"
  manpage "manpages/qurl-publish.1"
  manpage "manpages/qurl-restart.1"
  manpage "manpages/qurl-share.1"
  manpage "manpages/qurl-start.1"
  manpage "manpages/qurl-status.1"
  manpage "manpages/qurl-stop.1"
  manpage "manpages/qurl-version.1"
  manpage "manpages/qurl-whoami.1"
  manpage "manpages/qurl.1"
  bash_completion "completions/qurl.bash"
  fish_completion "completions/qurl.fish"
  zsh_completion "completions/qurl.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qurl"] if OS.mac?
  end

  # No zap stanza required
end
