# This file was generated by GoReleaser. DO NOT EDIT.
cask "qurl" do
  version "2.3.2"

  on_macos do
    on_arm do
      sha256 "9a1d4521838abd79573254a7dac17cdb86f720974e68a3d517c40571bb077089"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_darwin_arm64.tar.gz",
          verified: "github.com/layervai/qurl-integrations/releases/download"
    end
    on_intel do
      sha256 "6a946486c83ceca21e11bd5ff5d3bb7f6fc378c7546c085be74022ce1f6eb0d5"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_darwin_amd64.tar.gz",
          verified: "github.com/layervai/qurl-integrations/releases/download"
    end
  end
  on_linux do
    on_arm do
      sha256 "02dfdcdc216d530dc15b6efc5db54996db9dcc52b8c7566cd1b9a367171f6d04"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_linux_arm64.tar.gz",
          verified: "github.com/layervai/qurl-integrations/releases/download"
    end
    on_intel do
      sha256 "010c1e12d61bad199b350ad47ea342f4bb4644243e7be713929675211a69765e"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_linux_amd64.tar.gz",
          verified: "github.com/layervai/qurl-integrations/releases/download"
    end
  end

  name "qurl"
  desc "Publish and access protected resources"
  homepage "https://layerv.ai/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qurl"
  manpage "manpages/qurl-completion.1"
  manpage "manpages/qurl-daemon-run.1"
  manpage "manpages/qurl-daemon.1"
  manpage "manpages/qurl-delete.1"
  manpage "manpages/qurl-get.1"
  manpage "manpages/qurl-inspect.1"
  manpage "manpages/qurl-list.1"
  manpage "manpages/qurl-login.1"
  manpage "manpages/qurl-publish.1"
  manpage "manpages/qurl-restart.1"
  manpage "manpages/qurl-share.1"
  manpage "manpages/qurl-start.1"
  manpage "manpages/qurl-status.1"
  manpage "manpages/qurl-stop.1"
  manpage "manpages/qurl-version.1"
  manpage "manpages/qurl-whoami.1"
  manpage "manpages/qurl.1"
  bash_completion "completions/qurl.bash"
  fish_completion "completions/qurl.fish"
  zsh_completion "completions/qurl.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qurl"] if OS.mac?
  end

  # No zap stanza required
end
