# This file was generated by GoReleaser. DO NOT EDIT.
cask "qurl" do
  version "2.0.2"

  on_macos do
    on_arm do
      sha256 "f9b1d6c060d5a59e51b13488bb17f3a57e18a042d10658863ab5a073285c28b9"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/layervai/qurl-integrations/releases/download"
    end
    on_intel do
      sha256 "d8dff1d0c4058dd84a05f11f6f9a74a5068ea2ccac011d7cd70d531a42468b6b"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/layervai/qurl-integrations/releases/download"
    end
  end
  on_linux do
    on_arm do
      sha256 "7b4587e6811d61c14f10882174156f8964e08136fb704bae5861863e171059dd"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_linux_arm64.tar.gz",
        verified: "github.com/layervai/qurl-integrations/releases/download"
    end
    on_intel do
      sha256 "f6f48126bb443707035db9b0d558e99b13219c001cb493a0eb541fdf1845a7eb"
      url "https://github.com/layervai/qurl-integrations/releases/download/v#{version}/qurl_#{version}_linux_amd64.tar.gz",
        verified: "github.com/layervai/qurl-integrations/releases/download"
    end
  end

  name "qurl"
  desc "qURL CLI - manage secure links from the command line"
  homepage "https://layerv.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qurl"
  manpage "manpages/qurl-completion.1"
  manpage "manpages/qurl-delete.1"
  manpage "manpages/qurl-get.1"
  manpage "manpages/qurl-list.1"
  manpage "manpages/qurl-login.1"
  manpage "manpages/qurl-logout.1"
  manpage "manpages/qurl-publish.1"
  manpage "manpages/qurl-resolve.1"
  manpage "manpages/qurl-restart.1"
  manpage "manpages/qurl-start.1"
  manpage "manpages/qurl-status.1"
  manpage "manpages/qurl-stop.1"
  manpage "manpages/qurl-version.1"
  manpage "manpages/qurl-whoami.1"
  manpage "manpages/qurl.1"
  bash_completion "completions/qurl.bash"
  fish_completion "completions/qurl.fish"
  zsh_completion "completions/qurl.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qurl"]
    end
  end

  # No zap stanza required
end
